### ISSUE TITLE
ACE2005 evaluation

### ISSUE THREAD

**Issue by afonsoamendes** [berlino/nest-trans-em18#2]
We have been trying to replicate the settings for AC2005 but we can not find the right splits. Is it possible to have the splits? Do you also use the heads of the mentions?

Thanks 

Afonso

**Comment by berlino** [comment]
Hi, Afonso:

  Thanks for your interests. The split files can be found here http://www.statnlp.org/paper/joint-mention-extraction-and-classification-with-mention-hypergraphs.html by downloading a version, say 0.2. If you still can not find it, send me an email and I will get it to you. 

  I did not use the heads of mentions. But it is an interesting problem to extract the head of mentions and mentions at the same time. 

Bailin

**Comment by afonsoamendes** [comment]
Hi Bailin,

I downloaded version 0.2 but the number of mentions we get does not match with what is reported in the paper “A Neural Layered Model for Nested Named Entity Recognition” from Meizhi Ju, Makoto Miwa and Sophia Ananiadou which I thought was using the same splits that you have.

Could you check if the following numbers for the entity counts are correct and that you are using all of them (CL is entity Class, MT is mention type and ET is entity type):

Total TEST Spans = 3022
CL:SPC = 2418
CL:GEN = 341
CL:USP = 258
CL:NEG = 5

MT:PRO = 1010
MT:NOM = 1091
MT:NAM = 921

ET:PER = 1717
ET:ORG = 529
ET:GPE = 435
ET:LOC = 54
ET:FAC = 136
ET:VEH = 101
ET:WEA = 50


Total DEV Spans = 3215
CL:SPC = 2448
CL:GEN = 321
CL:USP = 429
CL:NEG = 17

MT:PRO = 1139
MT:NOM = 1142
MT:NAM = 934

ET:PER = 1684
ET:ORG = 400
ET:GPE = 682
ET:LOC = 101
ET:FAC = 162
ET:VEH = 82
ET:WEA = 104


Total TRAIN Spans = 24691
CL:SPC = 19112
CL:USP = 3053
CL:GEN = 2446
CL:NEG = 80

MT:PRO = 8162
MT:NOM = 8837
MT:NAM = 7692

ET:PER = 13258
ET:ORG = 3795
ET:GPE = 4759
ET:LOC = 757
ET:FAC = 880
ET:VEH = 584
ET:WEA = 658

Thanks,

Afonso

**Comment by berlino** [comment]
Yes, they used a different split and I explicitly mentioned that in the footnote 8.

**Comment by afonsoamendes** [comment]
Thanks, I see it now. Could you confirm the numbers I sent?

Thanks a lot for the prompt responses.

Afonso

**Comment by berlino** [comment]
Detailed statistics can be found in the supplementary material from another paper. Here is the [link](http://www.statnlp.org/research/ie/emnlp2018-semi-supp.pdf).

**Comment by afonsoamendes** [comment]
Thanks, that’s exactly what I needed.

Afonso
